version: '3.7'

services:
  django: &django
    image: godiel/django_task:latest
    networks:
      - gropoz-network
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.mysql
    volumes:
      - ./celery_beat_schedule:/celery_beat_schedule
    command: /start
    ports:
      - "8000:5000"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - gropoz-network

  celery_worker:
    <<: *django
    image: godiel/django_task:latest
    depends_on:
      - redis
    ports: [ ]
    command: /start-celery-worker
    networks:
      - gropoz-network

  celery_beat:
    <<: *django
    image: godiel/django_task:latest
    depends_on:
      - redis
    ports: [ ]
    command: /start-celery-beat
    networks:
      - gropoz-network

networks:
    gropoz-network:
      external: true
