version: '3.7'


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: apps_production_django
    networks:
      - gropoz-network
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    ports:
      - "5000:5000"

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - gropoz-network

  celery_worker:
    <<: *django
    image: apps_production_celery_worker
    depends_on:
      - redis
    ports: [ ]
    command: /start-celery-worker
    networks:
      - gropoz-network

  celery_beat:
    <<: *django
    image: apps_production_celery_beat
    depends_on:
      - redis
    ports: [ ]
    command: /start-celery-beat
    networks:
      - gropoz-network


networks:
    gropoz-network:
      external: true
