# Generated by Django 4.2 on 2025-03-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0002_auto_20211221_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogsmodel',
            name='client_ip_data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
