#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python << END
import sys
import time

suggest_unrecoverable_after = 30
start = time.time()
import MySQLdb

while True:
    try:
        sys.stderr.write("Attempting to connect to MySQL...\n")
        _db = MySQLdb._mysql.connect(
            host="${MYSQL_HOST}",
            user="${MYSQL_USER}",
            password="${MYSQL_PASSWORD}",
            database="${MYSQL_DATABASE}",
            port=int("${MYSQL_PORT}")
        )
        sys.stderr.write("Connected to MySQL successfully!\n")
        break
    except MySQLdb._exceptions.OperationalError as error:
        sys.stderr.write(f"Connection failed: {error}\n")
        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write(f"This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{error}'\n")
    time.sleep(1)

END

exec "$@"
